trigger: none

# schedules:
# - cron: "*/10 * * * *"
#   displayName: Run every 10 minutes
#   branches:
#     include:
#     - main
#   always: true

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- script: |
    "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ^
      KickoffTHTestLib/KickoffTHTestLib.csproj ^
      /p:Configuration=Release ^
      /p:Platform=AnyCPU
  displayName: Build KickoffTHTestLib

- script: |
    .\KickoffTHTestLib\bin\Release\KickoffTHTestLib.exe
  displayName: Run KickoffTHTestLib
