trigger: none

# schedules:
# - cron: "*/2 * * * *"   # 每 10 分钟
#   displayName: Run every 10 minutes
#   branches:
#     include:
#     - main
#   always: true

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: VSBuild@1
  inputs:
    solution: 'KickoffTHTestLib/KickoffTHTestLib.csproj'
    msbuildArgs: '/p:Configuration=Debug'
    platform: 'Any CPU'
    configuration: 'Debug'

- script: |
    .\KickoffTHTestLib\bin\Debug\KickoffTHTestLib.exe
  displayName: Run Scorpion Runner
